export const customOptions = {
  borderStyle: [
    'none',
    'hidden',
    'dotted',
    'dashed',
    'solid',
    'double',
    'groove',
    'ridge',
    'inset',
    'outset',
  ],
  listStyle: ['none'],
  cursor: [
    'auto',
    'default',
    'none',
    'context-menu',
    'help',
    'pointer',
    'progress',
    'wait',
    'cell',
    'crosshair',
    'text',
    'vertical-text',
    'alias',
    'copy',
    'move',
    'no-drop',
    'not-allowed',
    'e-resize',
    'n-resize',
    'ne-resize',
    'nw-resize',
    's-resize',
    'se-resize',
    'sw-resize',
    'w-resize',
    'ew-resize',
    'ns-resize',
    'nesw-resize',
    'nwse-resize',
    'col-resize',
    'row-resize',
    'all-scroll',
    'zoom-in',
    'zoom-out',
    'grab',
    'grabbing',
  ],
  display: [
    'block',
    'inline',
    'inline-block',
    'flex',
    'inline-flex',
    'grid',
    'inline-grid',
    'flow-root',
    'none',
    'contents',
    'table',
    'table-row',
    'list-item',
  ],
  outline: ['none'],
  textDecoration: ['none'],
  verticalAlign: [
    'baseline',
    'sub',
    'super',
    'text-top',
    'text-bottom',
    'middle',
    'top',
    'bottom',
  ],
  touchAction: [
    'auto',
    'none',
    'pan-x',
    'pan-left',
    'pan-right',
    'pan-y',
    'pan-up',
    'pan-down',
    'pinch-zoom',
    'manipulation',
  ],
  appearance: ['none', 'auto', 'textfield', 'menulist-button'],
  alignItems: [
    'normal',
    'stretch',
    'center',
    'start',
    'end',
    'flex-start',
    'flex-end',
    'baseline',
  ],
  backgroundClip: ['border-box', 'padding-box', 'content-box', 'text'],
  justifyContent: [
    'center',
    'start',
    'end',
    'flex-start',
    'flex-end',
    'left',
    'right',
    'normal',
    'space-between',
    'space-around',
    'space-evenly',
    'stretch',
  ],
}
